version: "2"
services:
  dojo:
    #restart: always
    #build: ../django-DefectDojo
    image: aweaver/defectdojo:latest
    ports:
      - "8000:8000"
    volumes:
      - django-DefectDojo:/django-DefectDojo
    depends_on:
      - mysql
    env_file:
      - .env
    command: bash ./django-DefectDojo/docker/docker-startup.bash
  mysql:
    restart: always
    image: mysql:latest
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: "dojo"
      MYSQL_USER: "dojodb"
      MYSQL_PASSWORD: "TPxqKVDRAIrOjK67aaoWWdbuK"
      MYSQL_ROOT_PASSWORD: "n26XJKqHIa6icJP80GegXFFfg"
      max_allowed_packet: "16M"
    volumes:
      - mysqldata:/var/lib/mysqldata/data/
  nginx:
    restart: always
    build: ./nginx/
    ports:
      - "80:80"
      - "443:443"
    expose:
      - "80"
      - "443"
    environment:
     - DH_SIZE=512
    volumes_from:
      - dojo
    volumes:
      - nginxdata:/etc/nginx/external/
    depends_on:
      - dojo
volumes:
  mysqldata: {}
  django-DefectDojo: {}
  nginxdata: {}
